### ISSUE TITLE
Using TLS 1.2 from Flask-LDAPConn example throws exception

### ISSUE THREAD

**Issue by DelboyJay** [rroemhild/flask-ldapconn#21]
Hi,

I have tried your example given [here](https://pypi.python.org/pypi/Flask-LDAPConn) But it seems to raises an exception because LDAP_TLS_VERSION = ssl.PROTOCOL_TLSv1_2 is used. I'm trying to use TLS1.2 over port 389.

This was working it seems when I used the following package versions:
```
Flask==0.10.1
Flask-LDAPConn==0.6.12
ldap3==1.2.2
```

Now I have updated to the following versions and it no longer works:
```
Flask==0.12
Flask-LDAPConn==0.6.13
ldap3==1.3.1
```

Here is the code I was using which is based directly on your example. 

```
import ssl

from flask import Flask, current_app
from flask_ldapconn import LDAPConn
from ldap3 import SUBTREE

LDAP_SERVER = '<DCName>'  # Domain Controller machine name
LDAP_BASEDN = 'DC=<mycompany>,DC=<loca>l'
LDAP_BINDDN = '<username>'  # Username
LDAP_SECRET = "<password>"  # Password

LDAP_PORT = 389
LDAP_TIMEOUT = 10
LDAP_USE_TLS = True  # default
LDAP_REQUIRE_CERT = ssl.CERT_NONE  # default: CERT_REQUIRED
LDAP_TLS_VERSION = ssl.PROTOCOL_TLSv1_2  # default: PROTOCOL_TLSv1

SECRET_KEY = "shhh... it's a secret!"

HTTP_ADDR = 'localhost'
HTTP_PORT = 8000
DEBUG = True

app = Flask(__name__)


@app.route('/')
def index():
    try:
        ldapc = current_app.ldap.connection
        search_filter = '(&(samaccounttype=805306368) (samaccountname=%s))'
        attributes = ['sn', 'givenName', 'uid', 'mail']
        ldapc.search(current_app.config["LDAP_BASEDN"], search_filter, SUBTREE,
                     attributes=attributes)
        response = ldapc.response
    except Exception as ex:
        raise


def main():
    app.config.from_pyfile(__file__)
    app.ldap = LDAPConn(app)
    app.run(app.config["HTTP_ADDR"], app.config["HTTP_PORT"], debug=True)


if __name__ == '__main__':
    main()
```

When you access the main page from a browser the following exception is thrown:

```
ldap3.core.exceptions.LDAPStartTLSError: ('wrap socket error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)',)

Traceback (most recent call last):
  File "D:\venv\testserver\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\venv\testserver\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "D:\venv\testserver\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\venv\testserver\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "D:\venv\testserver\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\venv\testserver\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\venv\testserver\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\venv\testserver\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "D:\venv\testserver\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\venv\testserver\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\testserver\ldaptest.py", line 30, in index
    CMD_ADD_EXCEPTION_BREAK, CMD_SMART_STEP_INTO, InternalConsoleExec, NetCommandFactory, \
  File "D:\venv\testserver\lib\site-packages\flask_ldapconn\__init__.py", line 119, in connection
    current_app.config['LDAP_SECRET']
  File "D:\venv\testserver\lib\site-packages\flask_ldapconn\__init__.py", line 96, in connect
    read_only=current_app.config['LDAP_READ_ONLY'],
  File "D:\venv\testserver\lib\site-packages\ldap3\core\connection.py", line 293, in __init__
    self.start_tls(read_server_info=False)
  File "D:\venv\testserver\lib\site-packages\ldap3\core\connection.py", line 1040, in start_tls
    if self.server.tls.start_tls(self) and self.strategy.sync:  # for async connections _start_tls is run by the strategy
  File "D:\venv\testserver\lib\site-packages\ldap3\core\tls.py", line 237, in start_tls
    return self._start_tls(connection)
  File "D:\venv\testserver\lib\site-packages\ldap3\core\tls.py", line 252, in _start_tls
    raise start_tls_exception_factory(LDAPStartTLSError, exc)(connection.last_error)
```

If I use the default of LDAP_TLS_VERSION = ssl.PROTOCOL_TLSv1 then it works but wanted to use TLS1.2.

Any ideas what this exception really means or if the code I'm now using is wrong for this version of Flask-LDAPConn?

Cheers,
Del

**Comment by rroemhild** [comment]
Updated to the latest ldap3 version in the `develop` branch. Tested with `ssl.PROTOCOL_TLSv1_2` on my workstation and works for me.

**Comment by rroemhild** [comment]
Feel free to reopen this issue if you still have this problem.
